FROM biowonks/mist-lib.base

LABEL BioWonks <biowonks@users.noreply.github.com>

COPY _common /app/_common
COPY bin /app/bin
COPY core-lib /app/core-lib
COPY seqdepot-lib /app/seqdepot-lib
COPY mist-lib /app/mist-lib
COPY mist-api /app/mist-api
RUN chown -R biowonks:biowonks /app
USER biowonks
WORKDIR /app/mist-api
RUN npm install
CMD ["npm", "start"]
