/* eslint-disable no-magic-numbers */

'use strict';

module.exports = [
  // 0
  {
    coreData: {
      id: '8pduSfpL50c3yCBL08_A9g',
      sequence: 'MNLTLTRRLWMGFALMALLTLTSTLVGWYNLRFISQVEKDNTQALIPTMNMARQLSEASAWELFAAQNLTSADNEKMWQAQGRMLTAQSLKINALLQALREQGFDTTAIEQQEQEISRSLRQQGELVGQRLQLRQQQQQLSQQIVAAADEIARLAQGQANNATTSAGATQAGIYDLIEQDQRQAAESALDRLIDIDLEYVNQMNELRLSALRVQQMVMNLGLEQIQKNAPTLEKQLNNAVKILQRRQIRIEDPGVRAQVATTLTTVSQYSDLLALYQQDSEISNHLQTLAQNNIAQFAQFSSEVSQLVDTIELRNQHGLAHLEKASARGQYSLLLLGMVSLCALILILWRVVYRSVTRPLAEQTQALQRLLDGDIDSPFPETAGVRELDTIGRLMDAFRSNVHALNRHREQLAAQVKARTAELQELVIEHRQARAEAEKASQAKSAFLAAMSHEIRTPLYGILGTAQLLADNPALNAQRDDLRAITDSGESLLTILNDILDYSAIEAGGKNVSVSDEPFEPRPLLESTLQLMSGRVKGRPIRLATAIADDMPCALMGDPRRIRQVITNLLSNALRFTDEGYIILRSRTDGEQWLVEVEDSGCGIDPAKLAEIFQPFVQVSGKRGGTGLGLTISSRLAQAMGGELSATSTPEVGSCFCLRLPLRVATAPVPKTVNQAVRLDGLRLLLIEDNPLTQRITIEMLKTSGAQIVAVGNAAQALETLQNSEPFAAALVDFDLPDIDGITLARQLAQQYPSLVLIGFSAHVIDETLRQRTSSLFRGIIPKPVPREVLGQLLAHYLQLQVNNDQSLDVSQLNEDAQLMGTEKIHEWLVLFTQHALPLLDEIDIARASQDSEKIKRAAHQLKSSCSSLGMHIASQLCAQLEQQPLSAPLPHEEITRSVAALEAWLHKKDLNAI',
    },
    coils: [
      [130, 150],
      [222, 242],
      [409, 443],
    ],
    segs: [
      [18, 25],
      [120, 143],
      [431, 446],
    ],
    tmhmm2: {
      topology: [
        ['o', 1, 9],
        ['M', 10, 32],
        ['i', 33, 330],
        ['M', 331, 353],
        ['O', 354, 914],
      ],
      tms: [
        [10, 32],
        [331, 353],
      ],
    },
  },

  // 1
  {
    coreData: {
      id: 'dYTwPLwRnTYVJoPa7itrFg',
      sequence: 'MKYLASFRTTLKASRYMFRALALVLWLLIAFSSVFYIVNALHQRESEIRQEFNLSSDQAQRFIQRTSDVMKELKYIAENRLSAENGVLSPRGRETQADVPAFEPLFADSDCSAMSNTWRGSLESLAWFMRYWRDNFSAAYDLNRVFLIGSDNLCMANFGLRDMPVERDTALKALHERINKYRNAPQDDSGSNLYWISEGPRPGVGYFYALTPVYLANRLQALLGVEQTIRMENFFLPGTLPMGVTILDENGHTLISLTGPESKIKGDPRWMQERSWFGYTEGFRELVLKKNLPPSSLSIVYSVPVDKVLERIRMLILNAILLNVLAGAALFTLARMYERRIFIPAESDALRLEEHEQFNRKIVASAPVGICILRTADGVNILSNELAHTYLNMLTHEDRQRLTQIICGQQVNFVDVLTSNNTNLQISFVHSRYRNENVAICVLVDVSSRVKMEESLQEMAQAAEQASQSKSMFLATVSHELRTPLYGIIGNLDLLQTKELPKGVDRLVTAMNNSSSLLLKIISDILDFSKIESEQLKIEPREFSPREVMNHITANYLPLVVRKQLGLYCFIEPDVPVALNGDPMRLQQVISNLLSNAIKFTDTGCIVLHVRADGDYLSIRVRDTGVGIPAKEVVRLFDPFFQVGTGVQRNFQGTGLGLAICEKLISMMDGDISVDSEPGMGSQFTVRIPLYGAQYPQKKGVEGLSGKRCWLAVRNASLCQFLETSLQRSGIVVTTYEGQEPTPEDVLITDEVVSKKWQGRAVVTFCRRHIGIPLEKAPGEWVHSVAAPHELPALLARIYLIEMESDDPANALPSTDKAVSDNDDMMILVVDDHPINRRLLADQLGSLGYQCKTANDGVDALNVLSKNHIDIVLSDVNMPNMDGYRLTQRIRQLGLTLPVIGVTANALAEEKQRCLESGMDSCLSKPVTLDVIKQTLTLYAERVRKSRDS',
    },
    coils: [
      [449, 469],
    ],
    segs: [
      [315, 330],
      [452, 472],
      [514, 527],
    ],
    tmhmm2: {
      topology: [
        ['o', 1, 19],
        ['M', 20, 42],
        ['i', 43, 314],
        ['M', 315, 334],
        ['O', 335, 949],
      ],
      tms: [
        [20, 42],
        [315, 334],
      ],
    },
  },

  // 2
  {
    coreData: {
      id: 'yg8A8H8N-4x1Ezf8WW-YbA',
      sequence: 'MTNVLIVEDEQAIRRFLRTALEGDGMRVFEAETLQRGLLEAATRKPDLIILDLGLPDGDGIEFIRDLRQWSAVPVIVLSARSEESDKIAALDAGADDYLSKPFGIGELQARLRVALRRHSATTAPDPLVKFSDVTVDLAARVIHRGEEEVHLTPIEFRLLAVLLNNAGKVLTQRQLLNQVWGPNAVEHSHYLRIYMGHLRQKLEQDPARPRHFITETGIGYRFML',
    },
    pfam31: [
      {
        name: 'Response_reg',
        score: 101.9,
        bias: 0,
        c_evalue: 2.5e-33,
        i_evalue: 2e-29,
        hmm_from: 1,
        hmm_to: 111,
        hmm_cov: '[.',
        ali_from: 4,
        ali_to: 112,
        ali_cov: '..',
        env_from: 4,
        env_to: 113,
        env_cov: '..',
        acc: 0.98,
      },
      {
        name: 'Trans_reg_C',
        score: 77.2,
        bias: 0,
        c_evalue: 8.2e-26,
        i_evalue: 6.7e-22,
        hmm_from: 2,
        hmm_to: 77,
        hmm_cov: '.]',
        ali_from: 148,
        ali_to: 223,
        ali_cov: '..',
        env_from: 146,
        env_to: 223,
        env_cov: '..',
        acc: 0.98,
      },
    ],
    agfam2: [
      {
        name: 'Response_reg',
        score: 101.9,
        bias: 0,
        c_evalue: 2.5e-33,
        i_evalue: 2e-29,
        hmm_from: 1,
        hmm_to: 111,
        hmm_cov: '[.',
        ali_from: 4,
        ali_to: 112,
        ali_cov: '..',
        env_from: 4,
        env_to: 113,
        env_cov: '..',
        acc: 0.98,
      },
      {
        name: 'Trans_reg_C',
        score: 77.2,
        bias: 0,
        c_evalue: 8.2e-26,
        i_evalue: 6.7e-22,
        hmm_from: 2,
        hmm_to: 77,
        hmm_cov: '.]',
        ali_from: 148,
        ali_to: 223,
        ali_cov: '..',
        env_from: 146,
        env_to: 223,
        env_cov: '..',
        acc: 0.98,
      },
    ],
  },

  // 3
  {
    coreData: {
      id: 'j4CpN55SAjIhp88GJS60zA',
      sequence: 'MSNQEPATILLIDDHPMLRTGVKQLISMAPDITVVGEASNGEQGIELAESLDPDLILLDLNMPGMNGLETLDKLREKSLSGRIVVFSVSNHEEDVVTALKRGADGYLLKDMEPEDLLKALHQAAAGEMVLSEALTPVLAASLRANRATTERDVNQLTPRERDILKLIAQGLPNKMIARRLDITESTVKVHVKHMLKKMKLKSRVEAAVWVHQERIF',
    },
    ecf1: [
      {
        name: 'ECF_999',
        ali_from: 91,
        ali_to: 206,
        ali_cov: '..',
        hmm_from: 1,
        hmm_to: 140,
        hmm_cov: '[]',
        score: 3.9,
        evalue: 2.8,
      },
    ],
  },
];
