create table taxonomy (
	id integer not null primary key,
	parent_taxonomy_id integer not null, -- Absolute root is 1
	name text not null,
	rank text
);

comment on column taxonomy.id is 'Actual NCBI taxonomy id - not auto generated by the database';
comment on column taxonomy.parent_taxonomy_id is 'parent taxonomy id';
comment on column taxonomy.rank is 'null if no rank is defined';

create index on taxonomy(parent_taxonomy_id);

-- MIGRATION DOWN SQL
drop table taxonomy;
